mala/datahandling/data_converter.py
mala/datahandling/data_handler.py
mala/descriptors/snap.py
mala/targets/density.py
mala/targets/dos.py
mala/targets/ldos.py

Paths should be joined using os.path.join() or tools from pathlib. Using
string concatenation is error-prone. For instance, DataHandler code
breaks if paths don't end in "/". I'm sure there is more, only fixed
what bit me.
Closes #195

Use os.path.join in DataHandler

---

.gitattributes
CITATION.cff

See https://citation-file-format.github.io/ for details. GitHub supports citation files, see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files. Zenodo added support for `CITATION.cff` as well. Once we got a DOI, we can add it to this file as well.
@RandomDefaultUser Please add all main package contributors as authors to this file with their correct affiliation.

Add Citation file

---

.bumpversion.cfg
setup.py

I've tested the config file, everything works as expected:
```sh
$ bumpversion minor
```
updates the version number in `mala/version.py` (and  with that in `setup.py`), `CITATION.cff` and `Copyright.txt` from `0.1.0` to `0.2.0`.

bumpversion

---

examples/ex01_run_singleshot.py
examples/ex02_preprocess_data.py
examples/ex03_postprocess_data.py
examples/ex04_hyperparameter_optimization.py
examples/ex05_training_with_postprocessing.py
examples/ex06_advanced_hyperparameter_optimization.py
examples/ex07_checkpoint_training.py
examples/ex08_checkpoint_hyperopt.py
examples/ex09_distributed_hyperopt.py
examples/ex10_tensor_board.py
install/data_repo_link/link_data_repo.sh
mala/datahandling/lazy_load_dataset.py
test/basic_gpu_test.py
test/checkpoint_hyperopt_tests.py
test/checkpoint_training_tests.py
test/hyperopt_test.py
test/inference_test.py
test/installation_test.py
test/integration_test.py
test/lazy_loading_test.py
test/tensor_memory.py
test/workflow_test.py

Updates data repo path. In the process, the tests now all include paths without trailing "/" and also I think I now found all the ugly string concats; Thus this PR closes #197 as well as #194 .

Updated data repo paths in tests and examples

---

.github/workflows/cpu-tests.yml
.github/workflows/gh-pages.yml

We change from using `GITHUB_TOKEN` to a ssh-key pair to enable PRs from forks to actually deploy our GitHub pages - but only when reviewed and approved by members with privilges (maintainer, owner) of mala.
We remove `ACCESS_TOKEN` as is it is no longer needed to access the `test-data` repository (it became public).

Change auth mechanism for deploy steps in workflows

---

.github/workflows/cpu-tests.yml
Dockerfile

This PR closes #254 and
- fixes/enables caching of Docker layers while building Docker image
- uses `latest` or `x.x.x` tag as Docker tags depending on trigger events (PR, git tag push, push to `master` or `develop`)
- is a first improvement on when to build and how to tag Docker images
Currently, the build process only runs successfully when one of the trigger events is triggered by a member/owner/maintainer from within the MALA repository. A PR from a forked repository is not allowed to push the Docker image built in the workflow to the container registry and fails with the message
```
denied: installation not allowed to Write organization package
Error: Process completed with exit code 1.
```
We need to clarify in a separate issue how the Docker build/push process of PRs should be …

Fix build docker images workflow

---

.github/workflows/cpu-tests.yml
Dockerfile

Adding `pytest`, `oapackage` and `pqkmeans` avoids installing these
packages within each CI run which is rather time consuming.
At least `oapackage` is not installable via Conda, one has to use `pip`
instead. In order to install those packages inside the `mala-cpu` or
`mala-gpu` environment one has to use the `pip` binary from inside these
conda environments. Usually one would do
```sh
$ conda activate mala-cpu
(mala-cpu)$ pip install oapackage
```
An alternative way is to directly use the `pip` binary from the
environment.
CMake is a dependency of `pqkmeans`. Finally, we are forced to switch to
the `latest` basis image which is based on Debian 11 and comes with a
recent SWIG version (4.0.2) needed for `oapackage`.

Add optional MALA dependencies to Docker image:

---

.github/workflows/cpu-tests.yml

Adds a check if the Conda environment aligns with the dependencies in the `requirements.txt`. If dependencies were added to `requirments.txt`, but were forgotten to be added to the Conda environment, then this test would fail and signal a misalignment between Conda environment in the Docker image and Mala's dependencies (and pssoible extra dependencies).

Add test to CPU workflow

---

mala/network/predictor.py
mala/targets/ldos.py

This fixes the "calculate SNAP descriptors on x ranks, gather them on rank 0, and work there with 1 GPU case". This case is a LEGACY use case. In the future, full parallel operations should be used. But until we have the total energy module running in parallel, this legacy case is needed.

Fixed predictor for operating on 1 GPU

---

.github/workflows/cpu-tests.yml

The workflow for the CPU tests now behaves as follows:
`build-docker-image-cpu`:
- check if cache is available and restore `docker-image.tar.gz` if it exists in the cache (Cache key is `github.run_id`, which changes for every new workflow run _except_ for multiple workflow runs within a PRs, e.g. by pressing the re-run workflow button, or when commits are added to the workflow. This avoids building the local Docker image again and again, which most likely is very time consuming. However, if the `cpu-tests.yml` file is repeatedly changed in one and the same PR, this will also result in a new run ids)
- pull `mala_conda_cpu:latest` image from MALAs container registry at `ghcr.io/mala`
- build local Docker image (the `Dockerfile` may have changed)
- compare local built Docker image with …

Complete rewrite of the cpu-tests workflow

---

.github/workflows/gh-pages.yml

If the review is approved, a run of the pipeline was triggered but
failed due to insufficient rights from the forked repository. There is
actually no need for an extra run of the pipeline once a review is
approved since a push to master or develop is likely to follow. This
merge/push is done with sufficient rights of the repositories owners.
Fixes #212

Avoids pipeline trigger on approved reviews:

---

docs/source/conf.py

Since we have long been public, we can reactivate the `viewcode` extension again, which allows to jump to the code from within the docs.

Reactivate sphinx' viewcode extension

---

.github/workflows/gh-pages.yml

With this we only have one place to maintain for the API docs.

Using make apidocs also in the GH workflow

---

docs/make.bat
docs/source/install/README.md
docs/source/install/tested_systems.rst
mala/network/network.py
test/hyperopt_test.py

The installation itself is trivial, as the default MALA installation only needs a few readily available packages, and puts everything else in the hand of the user. 
I had to alter one test, because through writing this I realized that `oapackage` was required for the test suite to run, which should not be the case. 
I also created a `make.bat` so the documentation may be built locally on Windows. 
Tested on a recent Windows 10. 
Closes #56 .

MALA on Windows

---

.github/workflows/cpu-tests.yml
Dockerfile

I was wrong about OAPackage 2.6.8 not working. It does. So we can fix #265  by downgrading oapackage safely.

Reverting OApackage to 2.6.8, so that miniconda3:4.9.2 can be used again

---

.github/workflows/publish-to-pypi.yml
README.md
setup.py

I've added secrets `TEST_PYPI_API_TOKEN` and `PYPI_API_TOKEN` to the mala settings.
On pushes to `master` and `develop` this workflow gets triggered and tries to build the mala package. On tags being pushed, the package will also be uploaded to TestPyPI. Only when a tag is turned into a release via GitHub, the package is published on PyPI.

Add workflow for publishing on PyPI and TestPyPI

---

docs/requirements.txt

They currently fail. I think the myst parser is to blame.

Fix the docs

---

mala/common/parallelizer.py
mala/common/parameters.py
mala/datahandling/lazy_load_dataset_clustered.py
mala/descriptors/snap.py
mala/interfaces/ase_calculator.py
mala/targets/ldos.py
mala/targets/target.py

Made mpi4py and pqkmeans loading per-demand, reduces loading time by 90%. The main time left is done by torch and optuna, but I don't really see a way around that. 
Closes #314 .

Reduced MALA import time

---

examples/ex12_run_predictions.py
mala/interfaces/ase_calculator.py
mala/network/trainer.py
mala/targets/calculation_helpers.py
mala/targets/density.py
mala/targets/dos.py
mala/targets/ldos.py
mala/targets/target.py
test/integration_test.py
test/workflow_test.py

Removed "_ev", "_eV", "_k" and "_K". MALA has standard units (all energies in eV, all temperatutes in K), so this is not needed for now.

Fixed naming for fermi energy and temperature variables

---

mala/descriptors/descriptor.py

To use the SNAP metric for e.g. learning the electronic density.

Enabled similarity metric for scalar in/output quantities

---

mala/descriptors/atomic_density.py

The missing grid dimensions were causing the issues with the gathering in the parallel case. Therefore fixes #387 .

Added missing grid dimensions for atomic density

---

.github/workflows/mirror-to-casus.yml

This PR fixes the mirror workflow. This was broken for months. 
With this PR I also wanted to enable host verification:
> To obtain the public key for the `GIT_SSH_KNOWN_HOSTS` secret, we have
issued the command `ssh-keyscan -t rsa github.com`.
However, this fails and will probably be fixed once [this PR](https://github.com/yesolutions/mirror-action/pull/19) of the mirror action used is merged.

Fix mirror workflow

---

examples/ex02_preprocess_data.py
examples/ex03_postprocess_data.py
examples/ex05_training_with_postprocessing.py
examples/ex15_ase_calculator.py
examples/ex17_visualize_electronic_structure.py
mala/datahandling/data_converter.py
mala/interfaces/ase_calculator.py
mala/network/predictor.py
mala/network/trainer.py
mala/targets/dos.py
mala/targets/target.py
test/inference_test.py
test/integration_test.py
test/interface_test.py
test/workflow_test.py

So instead of "qe.out" it is now called "espresso-out" as it would be in ASE. Further, I made the `data_type` parameter in "read_additional_calculation_data" optional, and MALA will now attempt to determine the type of file automatically.

Made output formats consistent with ASE

---

mala/targets/calculation_helpers.py
mala/targets/dos.py
mala/targets/ldos.py
mala/targets/target.py
test/integration_test.py

This adds a check to make sure that the calculation of exp(x) does not result in an overflow in the Fermi function. It gets rid of the Runtime warning encountered in #60 .

Added overflow check in Fermi function

---

mala/network/trainer.py

This PR fixes https://github.com/mala-project/mala/issues/427. The reason the bug occured was that the existing safeguard did not include the calculations on the actual, training data LDOS. But if no lazy loading is used, this data is scaled and rescaled as well, so any type of scaling that leads to un-integrable LDOS would throw this error. Simply moving this check into the safeguard restores expected behavior.

Fix `ValueError` for band energy metric

---

mala/common/parameters.py
mala/network/trainer.py

Added minus sign in front of early_stopping_threshold contribution to align behavior with description
Addresses issue #429

Make early_stopping_threshold behavior consistent with description

---

examples/ex02_test_network.py
examples/ex11_pass_single_feature.py
examples/ex12_run_predictions.py
mala/datahandling/data_handler.py
mala/network/hyper_opt.py
mala/network/runner.py
test/inference_test.py
test/lazy_loading_test.py
test/shuffling_test.py
test/workflow_test.py

This PR makes clear_data() the default behavior of the DataHandler initialization process. This makes testing and predicting way more robust w.r.t to small typing errors.

`clear_data` now default behavior

---

mala/common/parameters.py
mala/datahandling/data_converter.py
mala/datahandling/data_handler.py
mala/datahandling/lazy_load_dataset.py
mala/datahandling/lazy_load_dataset_clustered.py
mala/descriptors/atomic_density.py
mala/descriptors/bispectrum.py
mala/descriptors/descriptor.py
mala/descriptors/lammps_utils.py
mala/network/predictor.py
mala/targets/density.py
mala/targets/ldos.py

Since pytorch operates with FP32 anyway, it would be a good idea to have the data saved in FP32 too. This seemed like a problem since LDOS integration seemed to go wrong when performed with FP32 data, but this was an oversight in the usage of the `np.sum` function. This PR fixes this, closes #433 and allows for native training data conversion into FP32. FP64 conversion is supported as legacy option.

Save and load training data in FP32

---

mala/network/tester.py

Added an optional argument to predict_targets() and test_snapshot() allowing the user to specify 'tr' and 'va' partitions for testing.
This allows the user to easily calculate unscaled training and validation predictions for comparing accuracy between data set partitions.

Generalize Tester class to test training and validation partitions

---

mala/targets/density.py
mala/targets/ldos.py

For LDOS and density, the grid dimensions are now read alongside raw ab-initio data.

For LDOS and density, the grid dimensions are now read

---

mala/common/physical_data.py
mala/datahandling/data_handler_base.py
mala/datahandling/data_shuffler.py

The data shuffling is relatively trivial to parallelize over the newly created shuffled checkpoints.
Processes cannot easily cooperate in the creation of one single checkpoint as the shuffling operation is global within one checkpoint.
So, this PR distributes the to-be-created checkpoints over parallel workers. The input checkpoints are accessed in parallel. This parallel access does not really scale to full system size, but since there is only ever a mediocre number of checkpoints, such scaling is not really necessary.
An alternative would be to access input checkpoints one after another in parallel, but this has performance impacts (checkpoints might be opened and closed multiple times if multiple shuffled checkpoints are created per process), and processes would have to ensure that …

openPMD: shuffle data in parallel

---

test/hyperopt_test.py

Since the values we are comparing here are dependent on the eigensolver  implementation and numerical noise effects, I think it is reasonable to not require strict accuracy.

Adjusted NASWOT accuracy

---

external_modules/total_energy_module/build_total_energy_module.sh

Fix possible TEM build silent fail

---

mala/network/trainer.py

Due to some recent performance changes in the MALA GPU usage, using multiple GPUs in the Optuna distributed framework on single nodes would crash. This was due to the way MALA initializes the GPU assignments, leading to the `torch.cuda.synchronize()` initially having the wrong target device. Fixed by targeting correct device for `torch.cuda.synchronize()`.

Fixed distributed Optuna running on multiple GPUs

---

mala/descriptors/descriptor.py

Warning for users when pre-processing SNAP with lammps.  This is a temporary workaround for issue #502

Add warning for lammps pre-processing

---

external_modules/total_energy_module/total_energy.f90

A rogue PAW line in the total energy module lead to occasional installation issues

Fixed total energy module installation

---

mala/network/tester.py

@timcallow found the bug, this should fix it.

Hotfixing a problem with DOS comparison in the Tester class

---

docs/source/advanced_usage/descriptors.rst
docs/source/advanced_usage/predictions.rst
docs/source/basic_usage/more_data.rst
docs/source/citing.rst
docs/source/conf.py
docs/source/index.md
docs/source/install/installing_lammps.rst
docs/source/installation.rst
install/mala_cpu_base_environment.yml
install/mala_cpu_environment.yml
mala/common/parameters.py
mala/descriptors/atomic_density.py
mala/descriptors/bispectrum.py
mala/descriptors/descriptor.py
requirements.txt
test/complete_interfaces_test.py
test/descriptor_test.py
test/hyperopt_test.py
test/workflow_test.py

This PR implements the calculation of bispectrum and Gaussian descriptors in python. This implementation is significantly slower than LAMMPS and has some other restrictions, but it is fast and general enough to be used as a fallback during development and CI testing. Its intended audience are developers and students who did not set up LAMMPS yet or the CI. 
The idea of having MALA do bispectrum calculations independently of other codes had been flowing around for a while. One of the main issues with being dependent on external libraries, from my point of view, is getting started with the code. Multiple times I have interacted with students who just wanted to try out some small part of the code, but did not want to set up LAMMPS and QE themselves. Therefore this PR and a similar one for …

Descriptor calculation in python

---

.pre-commit-config.yaml
docs/source/CONTRIBUTE.md
docs/source/conf.py
setup.py

As suggested in #501, this adds `.pre-commit-config.yaml` to help `black` adoption. 
This doesn't enforce anything. If people don't use `pre-commit` locally, this has no effect. It however defines the `black` version and thus the formatting rules that the project wishes to see applied.
This PR also formats `setup.py` and `docs/source/conf.py`.

Add `pre-commit` config, format remaining files

---

.github/workflows/cleanup.yml

This workflow removes (old) untagged `mala_conda_cpu` containers from the package registry. It can only be triggered manually, see https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow.
Closes #516

Add workflow to delete untagged containers

---

mala/common/physical_data.py
mala/datahandling/data_shuffler.py

Until now, the DataShuffler replaces the `*` pattern with the snapshot number before passing the file name to openPMD. It's better to set `%T` here so openPMD knows the structure of the filename. With this fix, the output data can be accessed as one data series with openPMD tooling, e.g.
```
> openpmd-ls Be_shuffled%T.in.h5
openPMD series: Be_shuffled%T.in
openPMD standard: 1.1.0
openPMD extensions: 0
data author: ...
data created: 2024-03-11 11:31:55 +0100
data backend: HDF5
generating machine: unknown
generating software: MALA (version: 1.2.1)
generating software dependencies: unknown
number of iterations: 2 (fileBased)
all iterations: 0 1 
number of meshes: 1
all meshes:
Bispectrum
number of particle species: 0
franzpoeschel:~/git-repos/mala/examples/advanced
> openpmd-ls …
```

Remove hardcoded iteration number from data shuffler

---

mala/network/hyper_opt_optuna.py
test/hyperopt_test.py

Closes #497 
The test works, the only strange thing which is a bit unclear is documented in [this comment](https://github.com/mala-project/mala/blob/acff38534c8a0c4c7fcf1ee7a469f26b99343b5d/test/hyperopt_test.py#L464-L482).

Fix requeue zombie trials

---

mala/descriptors/atomic_density.py
mala/descriptors/bispectrum.py
mala/descriptors/descriptor.py
mala/descriptors/minterpy_descriptors.py
mala/targets/target.py

This PR adds a timestamp functionality to the creation of all temporary files for LAMMPS based descriptor calculations. This solves the issue documented in #502. 
Also implements automatic cleanup of temporary files by default (may be disabled by user if temporary files are needed for, e.g., debugging).

Timestamping LAMMPS temporary files

---

.github/workflows/gh-pages.yml
docs/requirements.txt

I was not able to create the documentation locally with a recent Python 3.11 installation. The versions of some sub-dependencies differ between Python 3.8 and Python 3.11. One of the sub-dependencies from packages specified in `docs/requirements.txt` expects a more recent Sphinx version `>=5`:
```sh
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
This PR fixes this and other (`Node.js`) issues:

Update docs workflow and dependencies

---

.github/workflows/cpu-tests.yml
.github/workflows/gh-pages.yml
docs/source/CONTRIBUTE.md

This avoids unnecessary and expensive runs of the test pipelines.
Closes #514

Only trigger test and docs workflows when PR is makred as ready for review

---

.github/workflows/cleanup-caches.yml

Caches are only relevant as long as a PR stays open and the test workflows getting triggered multiple times (PR receives updates with additional commits).
Related to #528

Clean up caches to stay within GH's storage limit

---

.github/workflows/cleanup-caches.yml

Fixes "Error: Resource not accessible by integration". The event runs against the workflow and code from the base of the PR rather then workflow and code from the merge commit.

Grant workflows triggered by PR from access to secrets:

---

.github/workflows/cpu-tests.yml

Usage of the cache should speed up *multiple* workflow runs within PRs for fixing failed tests etc. So far even for pushes to `develop` and `master` branches (merge commit of PRs) the Docker image is also uploaded to the cache, but most likely won't get used afterwards and hence only occupies cached storage.

Restrict usage of cache to PRs:

---

.github/workflows/cpu-tests.yml

This reverts commit 138b8a79d554a6f98e58f0c3b080612d3feda2e7 and should fix the CI cpu-tests jobs for pushes to `develop` or `master`. I need to figure out a better way on how to clean caches after pushes to these branches.

Revert "Restrict usage of cache to PRs:"

---

.github/workflows/cpu-tests.yml
.github/workflows/gh-pages.yml

Finally closes #514
Specifying `if: ${{ ! github.event.pull_request.draft }}` is only required for the first job in `cpu-tests.yml` and `gh-paages.yml` as subsequent jobs in the respective workflow files depend on the first job. This means that if the first job is skipped due to a PR draft, all dependent jobs are also skipped, which is what we intend.

Allow CI runs for normal PRs, but avoid runs for draft PRs

---

mala/common/physical_data.py

This introduces a workaround for a parallel flushing bug in openPMD-api <= v0.15, see https://github.com/openPMD/openPMD-api/issues/1616 for the original issue and https://github.com/openPMD/openPMD-api/issues/1616 for the fix.
A fixed version is not yet released but it will be v0.16.
tldr version: explicitly write some Iteration attribute (here: `dt`) again to mark the Iteration as dirty so that the flushing logic will not accidentally skip it for collective flush operations.

openPMD I/O: fix parallel flushing

---

.github/workflows/cpu-tests.yml

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3.

This fixes Node.js 16 deprecation warnings in cpu-tests.yml

---

.github/workflows/cpu-tests.yml

The diffs of the two Conda environments (before and after installation of MALA inside the Docker container) are now displayed next to each other to make it easier to spot a discrepancy between the two.

Enhance diff output of Conda environments

---

Dockerfile
install/mala_cpu_base_environment.yml
install/mala_cpu_environment.yml
requirements.txt

Fix CI installation of openPMD-api

---

.github/workflows/cpu-tests.yml

This is a temporary fix to make the caching mechanism in the CI work again. Its currently broken due to a switch to BuildKit as the default builder for Docker Engine as of version 23.0 (2023-02-01), see https://docs.docker.com/engine/release-notes/23.0/#2300.
Closes  #527

Use legacy builder to build Docker image

---

.github/workflows/cpu-tests.yml

Some minor improvements on the `cpu-tests.yml` workflow.

Improve CI

---

mala/descriptors/atomic_density.py
mala/descriptors/bispectrum.py
mala/descriptors/descriptor.py
mala/descriptors/minterpy_descriptors.py

This PR uses Python's `tempfile` module to generate the names for the temporary lammps files (#525). It should avoid the issues we had using the timestamp to generate unique names.

Use tempfile module for lammps file generation

---

.pre-commit-config.yaml

pre-commit: don't fix python version

---

mala/datahandling/data_shuffler.py

This PR allows the user to specify an arbitrary number of snapshots during the data shuffling procedure, even if the snapshot number isn't an exact divisor of the number of grid points in each snapshot.
In the non-exact-divisor case, a very small number of data points is "left out". To give an idea what very small means, consider a typical grid of 200x200x200 points, and a user requesting up to 10,000 snapshots. From the graph below, we can see that no more than ~0.1% of the initial data is left out in any of these choices.
This PR is a fix for issue #509.
Right now, I've implemented this only for the numpy case, so it's not possible with openPMD. Frankly I've no idea how to do it for the latter. I don't know how many users are currently using openPMD AND want to use an arbitrary snapshot …

Flexible snapshot number for data shuffling

---

examples/advanced/ex09_align_ldos.py
mala/__init__.py
mala/datahandling/__init__.py
mala/datahandling/ldos_align.py
mala/datahandling/ldos_aligner.py

Aligns a set of LDOS vectors to a reference. Optionally, the LDOS vectors can also be truncated from the left and right. This makes learning easier when the LDOS vectors become non-zero at different points, and/or are truncated (due to finite number of bands) at different points, such as when different mass densities are considered.
Remaining tasks need to be done or at least discussed before merging:

Align LDOS vectors to a reference

---

docs/source/install/installing_mala.rst
mala/interfaces/ase_calculator.py
mala/network/runner.py
mala/network/trainer.py
mala/targets/calculation_helpers.py
mala/targets/density.py
mala/targets/dos.py
mala/targets/ldos.py
mala/targets/target.py

A collection of small bugfixes. 
- Renames deprecated SciPy imports (fixes #575)
- Gives correct test data repo branch (fixes #565)
- Makes naming of variables in `Runner` class consistent (partially addresses #566)

Small bugfixes

---

mala/common/parameters.py

This PR automatically adds the primary training  metric to the validation metrics if it isn't in the list already.

Automatically added during training metric to validation_metrics

---

mala/network/predictor.py
mala/targets/density.py

Useful for, e.g., measuring inference timings.

Overhauled time reporting

---

mala/targets/dos.py

Since the DOS is not volumetric, the default route in PhysicalData does not work.

Make from_numpy_file usable for DOS

---

examples/basic/ex06_ase_calculator.py
mala/interfaces/ase_calculator.py

Closes #566, see discussion on the matter there.

Renamed loading method in ASE calculator 

---

mala/targets/target.py

This implements the reading of atomic forces and energy contributions for debugging purposes.

Adding additional QE.out parsing

---

mala/targets/density.py
mala/targets/ldos.py

This PR addresses issue #576.
According to the Gaussian [documentation](https://gaussian.com/cubegen/), cube files are almost always in atomic units, and this is certainly the units used by QE, so it should be safe to make this assumption. 
I simply changed the default units for the `read_from_cube` functions. 
I also added a warning statement if users explicitly request the wrong units.

Change default units when reading from cube files

---

.github/workflows/cpu-tests.yml
Dockerfile
setup.py

Addressing issue #592 
Since the coverage reports a number of 62%, I've set the `--cov-fail-under` parameter to 60%, i.e. the CPU tests will fail if the coverage dips below that.
We could use a third-party app like [codecov](https://about.codecov.io/) if we want more functionality - for example then we could have a separate test for coverage. That's what I did for atoMEC. This could also be introduced in a future PR if considered useful. I'll leave it up to you @RandomDefaultUser

Add coverage to tests

---

external_modules/total_energy_module/total_energy.f90
mala/descriptors/bispectrum.py
mala/descriptors/descriptor.py
mala/interfaces/ase_calculator.py
mala/targets/density.py
mala/targets/target.py

With this PR, `tempfile` is now also available for the TEM. Fixes the last part of, and therefore closes, #525 .

Implemented `tempfile` for TEM

---

.github/workflows/gh-pages.yml
mala/interfaces/ase_calculator.py

Since pydocstyle has been updated, it should be possible to test the docstrings of properties as well now.

Revert pydocstyle command

---

mala/common/parameters.py
mala/descriptors/atomic_density.py
mala/descriptors/descriptor.py
mala/descriptors/in.bgrid.python
mala/descriptors/in.bgrid.twoelements.python
mala/descriptors/in.bgridlocal.python
mala/descriptors/in.bgridlocal_defaultproc.python
mala/descriptors/in.ggrid.python
mala/descriptors/in.ggrid_defaultproc.python

Deleted all instances of "SNAP" from MALA, as it will be deprecated starting in v1.3.0. The new term we use and encourage is "Bispectrum descriptors", to avoid confusion with SNAP as an ML-IAP.

Deprecating the name "SNAP" descriptors

---

mala/datahandling/data_shuffler.py
test/shuffling_test.py

As detailed by @timcallow in https://github.com/mala-project/mala/issues/564, our current shuffling can lead to information loss. This occurs when one requests a number of snapshots to be shuffled such that the total number of data points may be divisible by the new number of snapshots, while the individual number of grid points per snapshot are not. 
This PR fixes this behavior by making the behavior implemented in https://github.com/mala-project/mala/pull/570 the default. I.e., snapshot shuffling now means:
(1. If the user does not provide a number for the snapshot files to be _shuffled into_, it is implicitly assumed that `number_after_shuffling = number_before_shuffling`)
2. It is checked whether the individual snapshot grid can be divided by this new number of snapshots
3. If not, …

Fixing tiny information loss in shuffling

---

mala/datahandling/data_shuffler.py
test/shuffling_test.py

The current shuffling algorithm is not fully adapted to OpenPMD yet. This PR removes some inconsistencies and adds a ValueError to make clear to users what is actually happening. Arbitrary number of snapshot shuffling capabilities for OpenPMD soon.

Quickfixing OpenPMD Shuffling

---

mala/network/trainer.py

I recently realized that using the current `develop` branch of MALA does not reproduce the DDP scaling results achieved upon implementation (#466). Looking into the code, the issue is with the change in how the validation loss is calculated, which occured in #560. #560 unifies the error calculation throughout MALA, which is in general very helpful, but there is one small caveat that I didn't realize at that time: it uses `_forward_entire_snapshot` to compute predictions on the validation snapshots. That function is (apparently) not as parallelizable through DDP as the direct LDOS validation loss calculation implemented previously. Of course it has the advantage that it gives predictions *per snapshot* and one therefore can access band energy, total energy, etc. as metrics during training. …

Recovering DDP scalability

---

mala/datahandling/data_shuffler.py
test/shuffling_test.py

Shuffling openPMD data so far worked only if the number of output snapshots cleanly divides the first dimension of the input data. This PR overcomes that restriction.
TODO:

Add arbitrary shuffling for openPMD input

---

mala/common/parameters.py
mala/descriptors/atomic_density.py
mala/descriptors/bispectrum.py
mala/descriptors/minterpy_descriptors.py

This PR changes the behavior of `parameters.descriptors.lammps_compute_file` (and renames it to `custom_lammps_compute_file`). Originally, the idea of this parameter was to allow users to supply custom LAMMPS compute files while also saving the compute files used during inference. This PR keeps the former usage, which may be useful for debugging, but removes this "caching" feature, because it leads to problems when multiple types of descriptors are computed during the same inference (e.g., when Bispectrum and AtomicDensity descriptors are needed to calculate the total energy).

Make caching the descriptor calculation input files optional

---

.github/workflows/cpu-tests.yml

As per https://github.com/actions/runner-images/issues/11101.
If I understand correctly, we are already using the 22.04 in two places, and the 20.04 in a different one. I am not sure of the top of my head what the reason for this was, so for now I updated and we'll see what needs fixing.

Update runner to Ubuntu 22.04

---

docs/source/advanced_usage/hyperparameters.rst
docs/source/advanced_usage/trainingmodel.rst
examples/advanced/ex03_tensor_board.py
examples/advanced/ex06_distributed_hyperparameter_optimization.py
mala/common/parameters.py
mala/network/trainer.py

Renamed:
- `after_training_metric` -> `final_validation_metric`
- `validation_metrics` -> `logging_metrics`
- `validate_every_n_epochs` -> `logging_metrics_interval`
- `validate_on_training_data` -> `log_metrics_on_train_set`
- `_validate_network` -> `_evaluate_metrics`
and updated the documentation to warn about the energy metrics' impact on speed.

Rename validation settings (ref #636)

---

mala/datahandling/data_scaler.py
mala/network/runner.py
test/README.md

Modified: 
- `runner.py`
- `data_scaler.py`
- From now on, all scaler parameters will be saved as `.json` files. 
- Backward compatible: Detects if pickle scaler files are present. If present, corresponding json files will automatically be added to the appropriate location (or zip).
- `workflow_test.py` passed.
- Manually checked values of pickled scaler in test-data with converted json scaler.
- Manually checked if example training and test scripts run.

Added json functionality for data scaling
