mala-project/mala

README.md
=> Fixed publication in README

examples/ex09_distributed_hyperopt.py, mala/__init__.py, mala/common/parameters.py, mala/network/__init__.py, mala/network/hyper_opt_optuna.py, mala/network/hyperparameter_optuna.py, mala/network/no_training_pruner.py, mala/network/objective_base.py, mala/network/objective_no_training.py
Not necessarily finished with everything, but this works very well now.
=> Update optuna implementation

README.md
In preparation of the merge, I made some changes:
- Changed Austins affiliation (since his side of the work for this release was not done at Sandia)
- Added "Contributors" for people who contributed, but are not part of the core team (from our side these are student researchers, but this category could be relevant e.g. for outside collaborators who contributed a part of the code)
- Added ORNL as contributing institution
=> Fixed developers list / README

.github/workflows/cpu-tests.yml, .gitignore, examples/ex12_run_predictions.py, mala/__init__.py, mala/common/parameters.py, mala/descriptors/descriptor_base.py, mala/descriptors/snap.py, mala/network/__init__.py, mala/network/predictor.py, mala/network/runner.py, mala/targets/density.py, mala/targets/dos.py, mala/targets/ldos.py, mala/targets/target_base.py, test/inference_test.py, test/workflow_test.py
Tester class only handles input-output data pairs, with this class both can be done simultaneously.
=> Implemented Predictor class that allows for standalone predictions

examples/ex04_hyperparameter_optimization.py, mala/__init__.py, mala/network/__init__.py, mala/network/hyper_opt_oat.py, mala/network/objective_base.py, test/workflow_test.py
OAT now supports checkpointing, and supports the same options as optuna now.
=> OAT bugfixing

mala/datahandling/data_converter.py, mala/descriptors/snap.py, test/interface_test.py
=> Implement Parallel Data Converter

mala/datahandling/data_converter.py, mala/targets/ldos.py
Finally closes #237 .
Uses File I/O for LDOS gathering. This is not necessarily the most performant, but the bottleneck are the SNAP descriptors anyway.
=> Works locally on test data, now tests on cluster have to be done

examples/ex04_hyperparameter_optimization.py, examples/ex06_advanced_hyperparameter_optimization.py, examples/ex14_mala_md.py, examples/ex15_mala_md_parallel.py, mala/__init__.py, mala/common/parameters.py, mala/datahandling/data_handler.py, mala/interfaces/__init__.py, mala/interfaces/ase_calculator.py, mala/network/__init__.py, mala/network/hyper_opt_interface.py, mala/network/hyper_opt_naswot.py, mala/network/hyper_opt_optuna.py, mala/network/hyperparameter_interface.py, mala/network/naswot_pruner.py, mala/network/objective_naswot.py, test/hyperopt_test.py, test/interface_test.py
=> Renamed ASECalculator and everything NASWOT related.

.github/workflows/cpu-tests.yml, mala/__init__.py, mala/common/json_serializable.py, mala/common/parameters.py, mala/datahandling/__init__.py, mala/datahandling/snapshot.py, mala/network/__init__.py, mala/network/hyper_opt_base.py, mala/network/hyper_opt_oat.py, mala/network/hyper_opt_optuna.py, mala/network/hyperparameter_oat.py, mala/network/hyperparameter_optuna.py, mala/network/trainer.py, test/inference_test.py, test/interface_test.py, test/workflow_test.py
Parameters can now be saved as JSON files.
=> Implement JSON parameters

examples/ex02_preprocess_data.py, examples/ex16_calculate_acsd.py, mala/common/parameters.py, mala/datahandling/data_converter.py, mala/datahandling/data_handler.py, mala/datahandling/lazy_load_dataset.py, mala/descriptors/descriptor_base.py, mala/descriptors/snap.py, mala/network/predictor.py, test/hyperopt_test.py, test/parallel_run_test.py, test/workflow_test.py
Closes #235.
Also changes the parameters, so the data repo will have to be updated, but therefore finally fixes the somewhat annoying quirk that `descriptors_contains_xyz` was contained in ParametersData. 
Also, needs to be tested on the cluster.
=> Implemented ACSD into MALA

examples/ex01_run_singleshot.py, mala/common/parallelizer.py, mala/common/parameters.py, mala/datahandling/data_converter.py, mala/datahandling/data_handler.py, mala/datahandling/data_scaler.py, mala/descriptors/descriptor_base.py, mala/descriptors/snap.py, mala/network/hyper_opt_base.py, mala/network/hyper_opt_naswot.py, mala/network/hyper_opt_oat.py, mala/network/hyper_opt_optuna.py, mala/network/network.py, mala/network/objective_base.py, mala/network/objective_naswot.py, mala/network/predictor.py, mala/network/runner.py, mala/network/tester.py, mala/network/trainer.py, mala/targets/atomic_force.py, mala/targets/density.py, mala/targets/dos.py, mala/targets/ldos.py, test/basic_gpu_test.py, test/checkpoint_hyperopt_tests.py, test/checkpoint_training_tests.py, test/integration_test.py, test/lazy_loading_test.py
=> Added verbosity parameter for more fine-granular control over output

mala/descriptors/snap.py
=> SNAP descriptors can now be calculated and saved without xyz

.github/workflows/cpu-tests.yml, examples/ex01_run_singleshot.py, examples/ex04_hyperparameter_optimization.py, examples/ex05_training_with_postprocessing.py, examples/ex06_advanced_hyperparameter_optimization.py, examples/ex07_checkpoint_training.py, examples/ex08_checkpoint_hyperopt.py, examples/ex09_distributed_hyperopt.py, examples/ex10_tensor_board.py, examples/ex11_pass_single_feature.py, examples/ex12_run_predictions.py, examples/ex13_atomic_forces.py, examples/ex14_mala_md.py, examples/ex17_advanced_networks.py, mala/common/parameters.py, mala/datahandling/data_handler.py, mala/datahandling/snapshot.py, test/basic_gpu_test.py, test/checkpoint_hyperopt_tests.py, test/checkpoint_training_tests.py, test/hyperopt_test.py, test/inference_test.py, test/interface_test.py, test/lazy_loading_test.py, test/workflow_test.py
=> Combined the snapshot lists into one

.github/workflows/cpu-tests.yml, install/mala_cpu_environment.yml, test/hyperopt_test.py
See https://github.com/pytorch/pytorch/pull/69904
=> Fix CI `setuptools`  error

mala/common/parameters.py, mala/network/network.py
=> Providing too many activation functions works now

mala/targets/density.py, mala/targets/dos.py, mala/targets/ldos.py, mala/targets/target.py
Except for simpson/trapezoid grid integration, everything works for non-cubic cells now.
=> grid spacing based -> voxel based

.github/workflows/cpu-tests.yml, setup.py
=> Fixed `extra requires` (small typo)

.github/workflows/gh-pages.yml, docs/requirements.txt, docs/source/CONTRIBUTE.md, docs/source/conf.py
=> Update docs requirements

mala/datahandling/data_converter.py, mala/targets/ldos.py
Implemented a MPI based LDOS communication, which of course is more memory hungry, but if it can be afforded, makes preprocessing a matter of minutes.
=> Faster parallel ldos

install/mala_cpu_base_environment.yml, install/mala_cpu_environment.yml, requirements.txt
I tested it locally, and conda did not uninstall any other package. It tried to upgrade openssl and the ca-certificates, but since it was an upgrade, that seems unrelated.
=> Remove pandas (EDIT: ADDING pandas)

docs/source/conf.py, mala/__init__.py, mala/common/check_modules.py, mala/common/parameters.py, mala/datageneration/__init__.py, mala/datageneration/ofdft_initializer.py, mala/datageneration/trajectory_analyzer.py, mala/targets/target.py, setup.py
This PR (re-)implements features used for the OF-DFT-MD paper into `mala`, so the it can be cited properly. Also adds the OF-DFT-MD initializer, which was priorly not implemented (publicly) anywhere. 
Closes #313 .
=> Merge _some_ functionality of 'malada' back into 'mala'

mala/common/parameters.py, mala/network/hyper_opt_optuna.py, mala/network/multi_training_pruner.py, mala/network/objective_base.py
- Added an "early stopping" like stopping criterion for Optuna
- Added a pruner for multiple trainings per trial
=> Small Optuna improvements

mala/common/parameters.py
Useful for routine jobs on HPC systems. Closes #324
=> Added function for easy optuna set up on single multiGPU nodes

examples/ex02_preprocess_data.py, mala/datahandling/data_converter.py, mala/descriptors/snap.py, mala/targets/density.py, mala/targets/ldos.py
Added options for the DataConverter to process only target OR descriptor values one at a time, and process user specified keyword arguments.
=> Flexible data conversion

docs/requirements.txt
sphinx-markdown-tables is currently crashing
=> Fixing the docs pipeline

mala/datahandling/data_scaler.py, test/scaling_test.py
=> Fixed scaling problems for "None" and "feature-wise-normal" options

examples/ex16_observables.py, mala/common/parameters.py, mala/descriptors/descriptor.py, mala/descriptors/in.bgrid.python, mala/descriptors/in.bgrid.twoelements.python, mala/descriptors/in.bgridlocal.python, mala/descriptors/in.bgridlocal_defaultproc.python, test/inference_test.py, test/interface_test.py
Activated the switchflag for SNAP by default and made it an option aswell.
=> SNAP switchflag

docs/source/install/external_modules.rst, external_modules/README_LICENSE.md, external_modules/total_energy_module/LICENSE, external_modules/total_energy_module/build_total_energy_module.sh, external_modules/total_energy_module/prepare_qe.sh, external_modules/total_energy_module/total_energy.f90
=> Re-integrating TEM into MALA main code 

mala/interfaces/ase_calculator.py, mala/targets/target.py, test/interface_test.py
Implemented new interface for improved saving and loading of additional calculation data, which is needed for Monte Carlo interface checkpointing.
=> Adaptions for Monte Carlo interface

mala/datahandling/data_converter.py
This was a merge error; Fixes #385
=> Got rid of redundandt xyz component cutting

examples/ex01_run_singleshot.py, examples/ex05_training_with_postprocessing.py, examples/ex06_advanced_hyperparameter_optimization.py, examples/ex07_checkpoint_training.py, examples/ex10_tensor_board.py, examples/ex12_run_predictions.py, examples/ex14_advanced_networks.py, examples/ex15_ase_calculator.py, mala/datahandling/data_handler.py, mala/network/objective_base.py, mala/network/runner.py, test/basic_gpu_test.py, test/checkpoint_training_test.py, test/hyperopt_test.py, test/inference_test.py, test/interface_test.py, test/lazy_loading_test.py, test/workflow_test.py
=> Clean up data handling

docs/source/CONTRIBUTE.md
Added info about creating releases and adding dependencies.
=> Updating documentation

examples/ex17_visualize_electronic_structure.py, mala/common/physical_data.py, mala/targets/density.py, mala/targets/target.py
Also implemented writing of internally saved target data. Closes #384.
=> Fixed cubewriter for 4D data

mala/targets/density.py, test/inference_test.py
This test had immediate returns, as I realized that there was a bug in the way the atomic density was called.
=> Added test for atomic density TEM formula

mala/common/physical_data.py, mala/targets/density.py, mala/targets/target.py
Fixes bugs that may occur when saving/loading target data without attaching metadata or only an incomplete set of metadata.
=> Improved metadata handling with OpenPMD

mala/descriptors/atomic_density.py
This is done by adding "return_directly" option for parallel case.
=> Fixed atomic density based TEM for parallel

.gitignore, examples/ex01_train_network.py, examples/ex02_test_network.py, examples/ex04_postprocess_data.py, examples/ex05_hyperparameter_optimization.py, examples/ex07_checkpoint_training.py, examples/ex11_pass_single_feature.py, examples/ex12_run_predictions.py, examples/ex15_ase_calculator.py, mala/__init__.py, mala/common/parameters.py, mala/datahandling/data_scaler.py, mala/network/__init__.py, mala/network/network.py, mala/network/predictor.py, mala/network/runner.py, mala/network/trainer.py, test/checkpoint_training_test.py, test/inference_test.py, test/workflow_test.py
Implemented a unified interface for saving and loading models, which closes #295
=> Full model saving/loading

mala/network/acsd_analyzer.py
Made the class more in line with other hyperparameter classes and also refactored massively internally; this will make it easier to add new descriptors in the future.
=> Improved upon ACSD analysis

docs/source/install/README.md
=> Git LFS mentioned in docs now

test/hyperopt_test.py
=> Added a test for NASWOT

mala/common/physical_data.py, mala/datahandling/data_shuffler.py, mala/targets/density.py, mala/targets/target.py
See #417 for a closer description. Serial implementation for now.
TODO:
(I will revert the changes in the `/examples` folder again, I have them on a separate branch for my personal development comfort.)
=> Shuffle from openPMD datasets

examples/clean.sh
After running all examples, update list of artifacts to be removed.
=> examples: update clean script

mala/common/physical_data.py, mala/datahandling/lazy_load_dataset_single.py, mala/datahandling/multi_lazy_load_data_loader.py
This is the last ingredient needed to close #417
=> Implemented multi lazy loading for OpenPMD

mala/network/tester.py
Fixes ValueError when calculating observable errors in test_snapshot for bad/untrained networks.
=> Fix ValueError in test_snapshot

examples/ex19_ase_calculator_with_uncertainty.py
=> Modify example ex19 to execute training if needed

mala/common/parameters.py, mala/datageneration/trajectory_analyzer.py
This ports a MALADA feature to MALA. The feature is experimental for now and barely used, this is mainly for compliance with code publications.
=> Add uncorrelated snapshot parsing from MALADA to MALA

.github/workflows/cleanup-caches.yml
=> Remove caches after pushes to develop/master (+tags)

docs/source/advanced_usage/predictions.rst, docs/source/install/installing_lammps.rst, docs/source/install/installing_qe.rst
=> doc: link to GPU usage docs from lammps install section

.github/workflows/cpu-tests.yml
Report full diff of Conda environment.yml files before and after installation of MALA only when they differ.
=> Condition-based display of Conda environment diffs:

examples/advanced/ex03_tensor_board.py, mala/common/parameters.py, mala/network/trainer.py
=> Validation every N steps

docs/source/advanced_usage/predictions.rst, mala/common/parameters.py
=> Update GPU/production run docs

mala/common/parameters.py
=> Fix ParametersNetwork doc strings

mala/network/runner.py
A small refactoring I did a while back broke the DDP interface. This should fix it.
=> Fixing DDP training

mala/network/predictor.py, mala/network/runner.py, mala/network/tester.py, mala/network/trainer.py
Fixes https://github.com/mala-project/mala/issues/496 by adapting batch size if needed.
=> Adapt batch size in case of GPU graphs

mala/common/parameters.py, mala/descriptors/ace.py, mala/descriptors/acelib/ace_potential.py, mala/descriptors/acelib/clebsch_gordan_coupling.py, mala/descriptors/acelib/common_utils.py, mala/descriptors/acelib/coupling_utils.py, mala/descriptors/acelib/symmetric_group_manipulations.py, mala/descriptors/acelib/tree_sorting.py, mala/descriptors/acelib/wigner_coupling.py, mala/descriptors/acelib/young.py
Copy of https://github.com/mala-project/mala/pull/644 because I don't have push access there
=> ACE documentation updates

examples/advanced/ex06_distributed_hyperparameter_optimization.py, examples/advanced/ex11_preprocess_ace_descriptors.py, mala/network/trainer.py, test/descriptor_test.py
The test data did not yet include the ACE files, also there was a small issue with the HO tests.
=> Fixing ACE and HO tests

.gitignore, examples/advanced/ex01_checkpoint_training.py, examples/basic/ex01_train_network.py, examples/basic/ex05_run_predictions.py, examples/clean.sh, pyproject.toml, test/clean.sh
This is a collection of small things that have piled up over time. None of those add/remove features. Here is a summary of the commit messages:
* Ignore .pk files
* Used as altertive to .pkl (pickle files).
* pyproject.toml: add mypy config
* pyproject.toml: add ruff lint rules section
* basic/ex05: skip if total_energy not found
* We do this in test/workflow_test.py, so seems sensible to do it here as well.
* examples: remove test_ prefix from variables
* test_{network,trainer} -> {network,trainer}
* test: update clean script
* Remove files not covered so far, e.g. all *.db, *_vis dirs etc.
* examples: improve clean script
* Remove mala_vis dir. Remove code duplication. Recursively find dirs and go clean up there.
=> Various small improvements

docs/source/advanced_usage/hyperparameters.rst
As per https://github.com/mala-project/mala/issues/515#issuecomment-2850907250. Closes #515.
=> Added Optuna resume related docs
